name: Install Dependencies
description: Caches and installs Bun dependencies

inputs:
  cache-key-suffix:
    description: 'Suffix for the cache key to allow different caches per job'
    required: true

runs:
  using: composite
  steps:
    - name: Cache Bun files
      id: bun-cache
      uses: actions/cache@v4
      with:
        path: |
          $HOME/.bun/install/cache
          node_modules
        key: ${{ runner.os }}-bun-${{ inputs.cache-key-suffix }}-${{ hashFiles('bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-
          ${{ runner.os }}-

    - name: Install dependencies
      if: steps.bun-cache.outputs.cache-hit != 'true'
      shell: bash
      run: task install
