name: Install Dependencies
description: Caches and installs Bun dependencies

runs:
  using: composite
  steps:
    - name: Cache Bun files
      id: bun-cache
      uses: actions/cache@v4
      with:
        path: |
          $HOME/.bun/install/cache
          node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-
          ${{ runner.os }}-

    - name: Install dependencies
      if: steps.bun-cache.outputs.cache-hit != 'true'
      shell: bash
      run: task install
