version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: '12:00'
    timezone: Europe/Helsinki
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - nikoheikkila
  ignore:
  - dependency-name: node-yaml
    versions:
    - "> 4.0.0"
  commit-message:
    prefix: build
    include: scope
  rebase-strategy: disabled
