version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '12:00'
    timezone: Europe/Helsinki
  open-pull-requests-limit: 20
  target-branch: master
  reviewers:
  - nikoheikkila
  commit-message:
    prefix: build
    include: scope

