language: node_js

os:
  - linux
  - osx

node_js:
  - "node"
  - "lts/*"

before_install:
  - npm install -g yarn@latest

install:
  - yarn --frozen-lockfile --prefer-offline
  - yarn build

before_script:
  - yarn serve &

script:
  - yarn lint
  - yarn test:a11y

cache: yarn
