dist: xenial

language: node_js
node_js:
  - "12"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - libgconf-2-4

install:
  - yarn --frozen-lockfile --prefer-offline
  - yarn build

script:
  - yarn lint
  - yarn test:unit
  - yarn test:e2e
  - yarn test:a11y

cache:
  yarn: true
  directories:
    - ~/.cache
