language: node_js

os:
  - linux
  - osx

node_js:
  - "12"

addons:
  chrome: stable

install:
  - yarn --frozen-lockfile --prefer-offline
  - yarn build

script:
  - yarn lint
  - yarn test:unit
  - yarn test:e2e
  - yarn test:a11y

cache:
  directories:
    - ~/.cache
