version: "3"

includes:
  terraform:
    taskfile: ./infra/Taskfile.yml
    dir: ./infra

tasks:
  new:
    desc: Scaffold a new post or page
    interactive: true
    cmds:
      - bun run new.ts

  install:
    desc: Install dependencies with Bun
    run: once
    sources:
      - package.json
    generates:
      - bun.lock
    cmd: bun install --frozen-lockfile

  format:
    desc: Format codebase
    deps: [install]
    cmds:
      - bunx biome check --write .

  typegen:
    desc: Generate GraphQL TypeScript types
    deps: [install]
    status:
      - test -f src/gatsby-types.d.ts
    cmds:
      - bun run scripts/generate-types.ts

  lint:
    desc: Lint codebase for style issues
    deps: [install, typegen]
    cmds:
      - bunx tsc --noEmit
      - bunx biome check .

  test:
    desc: Run application test suite
    deps:
      - lint
    cmds:
      - task: test:unit
      - task: test:component
      - task: build
      - task: test:e2e

  test:unit:
    desc: Run unit tests
    deps: [install]
    cmds:
      - bunx vitest run --project=unit {{ .CLI_ARGS }}

  test:unit:watch:
    desc: Run unit tests in watch mode
    deps: [install]
    interactive: true
    cmds:
      - bunx vitest watch --project=unit

  test:component:
    desc: Run component tests
    deps: [install, playwright]
    cmds:
      - bunx vitest run --project=component {{ .CLI_ARGS }}

  test:component:watch:
    desc: Run component tests in watch mode
    deps: [install, playwright]
    interactive: true
    cmds:
      - bunx vitest watch --project=component

  test:e2e:
    desc: Run end-to-end tests
    deps: [install, playwright]
    cmds:
      - bunx playwright test {{.CLI_ARGS}}

  playwright:
    desc: Install Playwright browsers
    internal: true
    cmd: bunx playwright install --with-deps

  dev:
    desc: Serve the Gatsby development site
    cmds:
      - task: clean
      - bunx gatsby develop

  clean:
    desc: Clear build cache and artifacts
    cmds:
      - bunx gatsby clean
      - rm -f src/gatsby-types.d.ts

  build:
    desc: Build the Gatsby production site
    deps: [install]
    generates:
      - public/
      - .cache/
    env:
      NODE_ENV: production
    cmds:
      - bun run build

  serve:
    desc: Serve the Gatsby production site
    deps: [install]
    env:
      NODE_ENV: production
    cmds:
      - bunx gatsby serve -p 8000
