version: "3"
dotenv:
  - .env

tasks:
  new:
    desc: Scaffold a new post or page
    interactive: true
    cmds:
      - npx esno new.ts

  install:
    desc: Install dependencies with Yarn
    run: once
    sources:
      - package.json
      - yarn.lock
    generates:
      - node_modules/*
    cmds:
      - corepack enable
      - corepack prepare yarn@stable --activate
      - yarn --immutable

  format:
    desc: Format codebase
    deps: [install]
    cmds:
      - npx prettier --write .
      - npx eslint --fix .

  lint:
    desc: Lint codebase
    deps:
      - lint-style
      - lint-types

  lint-style:
    desc: Lint codebase for style issues
    deps: [install]
    cmds:
      - npx prettier --check .
      - npx eslint .

  lint-types:
    desc: Lint TypeScript files for incorrect typing
    deps: [install]
    sources:
      - ./**/*.{ts,tsx}
    cmds:
      - npx tsc --noEmit

  test:
    desc: Run application test suite
    deps:
      - lint
    cmds:
      - task: test-unit
      - task: test-e2e

  test-unit:
    desc: Run unit tests
    deps: [install]
    sources:
      - src/**/*.{ts,tsx}
    cmds:
      - npx vitest run

  test-e2e:
    desc: Run end-to-end tests
    deps: [install, build]
    cmds:
      - npx playwright install --with-deps
      - npx playwright test {{.CLI_ARGS}}

  dev:
    desc: Run development server
    deps:
      - task: dev-gatsby

  dev-gatsby:
    desc: Serve the Gatsby development site
    deps: [install]
    cmds:
      - yarn clean
      - yarn dev

  build:
    desc: Build the Gatsby production site
    deps: [install]
    generates:
      - public/
      - .cache/
    env:
      GATSBY_CPU_COUNT: logical_cores
      NODE_ENV: production
    cmds:
      - yarn build

  serve:
    desc: Serve the Gatsby production site
    deps: [install]
    env:
      NODE_ENV: production
    cmds:
      - yarn serve
