version: "3"
dotenv:
  - .env

tasks:
  new:
    desc: Scaffold a new post or page
    interactive: true
    cmds:
      - bun run new.ts

  install:
    desc: Install dependencies with Bun
    run: once
    sources:
      - package.json
    generates:
      - bun.lock
    cmd: bun install

  format:
    desc: Format codebase
    deps: [install]
    cmds:
      - bunx biome format --write .
      - bunx biome lint --fix .

  lint:
    desc: Lint codebase for style issues
    deps: [install]
    cmds:
      - bunx biome format .
      - bunx biome lint .

  test:
    desc: Run application test suite
    deps:
      - lint
    cmds:
      - task: test:unit
      - task: test:component
      - task: build
      - task: test:e2e

  test:unit:
    desc: Run unit and component tests
    deps: [install]
    cmds:
      - bun test --config=src/__tests__/unit/bunfig.toml {{ .CLI_ARGS }}

  test:unit:watch:
    desc: Run unit tests in watch mode
    deps: [install]
    interactive: true
    cmds:
      - task: 'test:unit'
        vars:
          CLI_ARGS: '--watch'

  test:component:
    deps: [install, playwright]
    cmds:
      - bunx vitest run

  test:component:watch:
    desc: Run unit tests in watch mode
    deps: [install, playwright]
    interactive: true
    cmds:
      - bunx vitest --watch

  test:e2e:
    desc: Run end-to-end tests
    deps: [install, playwright]
    cmds:
      - bunx playwright test {{.CLI_ARGS}}

  playwright:
    desc: Install Playwright browsers
    internal: true
    cmd: bunx playwright install --with-deps

  dev:
    desc: Run development server
    deps:
      - task: dev:gatsby

  dev:gatsby:
    desc: Serve the Gatsby development site
    deps: [install]
    cmds:
      - task: clean
      - bunx gatsby develop

  clean:
    desc: Clear build cache and artifacts
    cmds:
      - bunx gatsby clean

  build:
    desc: Build the Gatsby production site
    deps: [install]
    generates:
      - public/
      - .cache/
    env:
      GATSBY_CPU_COUNT: logical_cores
      NODE_ENV: production
    cmds:
      - bun run build

  serve:
    desc: Serve the Gatsby production site
    deps: [install]
    env:
      NODE_ENV: production
    cmds:
      - bunx gatsby serve -p 8000
