version: "3"
dotenv:
  - .env

tasks:
  new:
    desc: Scaffold a new post or page
    interactive: true
    cmds:
      - bun run new.ts

  install:
    desc: Install dependencies with Bun
    run: once
    sources:
      - package.json
    generates:
      - bun.lock
    cmd: bun install --frozen-lockfile

  format:
    desc: Format codebase
    deps: [install]
    cmds:
      - npx biome format --write .
      - npx biome lint --fix .

  lint:
    desc: Lint codebase for style issues
    deps: [install]
    cmds:
      - npx biome format .
      - npx biome lint .

  test:
    desc: Run application test suite
    deps:
      - lint
    cmds:
      - task: test-unit
      - task: test-e2e

  test-unit:
    desc: Run unit tests
    deps: [install]
    sources:
      - src/**/*.{ts,tsx}
    cmds:
      - npx vitest run

  test-e2e:
    desc: Run end-to-end tests
    deps: [install, build]
    cmds:
      - npx playwright install --with-deps
      - npx playwright test {{.CLI_ARGS}}

  dev:
    desc: Run development server
    deps:
      - task: dev-gatsby

  dev-gatsby:
    desc: Serve the Gatsby development site
    deps: [install]
    cmds:
      - npx gatsby clean
      - npx gatsby develop

  build:
    desc: Build the Gatsby production site
    deps: [install]
    generates:
      - public/
      - .cache/
    env:
      GATSBY_CPU_COUNT: logical_cores
      NODE_ENV: production
    cmds:
      - bun run build

  serve:
    desc: Serve the Gatsby production site
    deps: [install]
    env:
      NODE_ENV: production
    cmds:
      - npx gatsby serve -p 8000
