version: "3"

vars:
  TFPLAN: "tfplan"
  OP_ARGS: "--env-file='.env'"

tasks:
  format:
    desc: Format Terraform codebase
    cmds:
      - terraform fmt -recursive

  validate:
    desc: Format Terraform codebase
    cmds:
      - terraform fmt -recursive -check
      - terraform validate

  run:
    desc: Run Terraform commands
    cmd: op run {{ .OP_ARGS }} -- terraform {{ .command }} {{ .CLI_ARGS }}
    requires:
      vars: [command, OP_ARGS]

  init:
    desc: Initialize Terraform (local)
    run: once
    sources:
      - "./**/*.tf"
    generates:
      - .terraform.lock.hcl
    cmds:
      - task: run
        vars:
          command: "init"
      - task: validate

  plan:
    desc: Plan Terraform changes (local)
    deps: [init]
    sources:
      - "./**/*.tf"
      - "./**/*.yml"
      - ".terraform.lock.hcl"
    generates:
      - "{{ .TFPLAN }}"
    cmd:
      task: run
      vars:
        command: "plan -out={{ .TFPLAN }}"

  deploy:
    desc: Apply Terraform changes from plan file (local)
    deps: [plan]
    sources:
      - "{{ .TFPLAN }}"
    cmds:
      - task: run
        vars:
          command: "apply {{ .TFPLAN }}"

  ci:init:
    desc: Initialize Terraform (CI)
    cmds:
      - terraform init
      - task: validate

  ci:plan:
    desc: Plan Terraform changes (CI)
    cmd: terraform plan -out={{ .TFPLAN }}

  ci:deploy:
    desc: Apply Terraform changes from plan file (CI)
    cmd: terraform apply {{ .TFPLAN }}
