name: Setup Development Environment
description: Sets up Node.js, Bun, and Task for the workflow

runs:
  using: composite
  steps:
    # Despite using Bun, we need Node.js for Gatsby to build correctly.
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install Task
      uses: go-task/setup-task@v1
