name: Setup Development Environment
description: Sets up Node.js, Bun, and Task for the workflow

runs:
  using: composite
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install Task
      uses: go-task/setup-task@v1
