/**
 * @see https://github.com/itgalaxy/generate-robotstxt#usage
 */
interface Policy {
	userAgent: string;
	disallow: string;
	allow?: string;
	crawlDelay?: number;
	cleanParam?: string;
}

/**
 * @see https://github.com/ai-robots-txt/ai.robots.txt/blob/main/robots.txt
 */
export const disallowedCrawlers = new Set([
	"AddSearchBot",
	"AI2Bot",
	"Ai2Bot-Dolma",
	"aiHitBot",
	"AmazonBuyForMe",
	"atlassian-bot",
	"amazon-kendra-",
	"Andibot",
	"Anomura",
	"anthropic-ai",
	"Awario",
	"bedrockbot",
	"bigsur.ai",
	"Bravebot",
	"Brightbot 1.0",
	"BuddyBot",
	"Bytespider-commercial",
	"ChatGPT Agent",
	"ChatGPT-User",
	"ChatGPT-User/2.0",
	"Claude-SearchBot",
	"Claude-User",
	"Claude-Web",
	"Cloudflare-AutoRAG",
	"CloudVertexBot",
	"cohere-ai",
	"cohere-training-data-crawler",
	"Cotoyogi",
	"Crawlspace",
	"Datenbank Crawler",
	"DeepSeekBot",
	"Devin",
	"Diffbot",
	"DuckAssistBot",
	"Echobot Bot",
	"EchoboxBot",
	"FacebookBot",
	"Factset_spyderbot",
	"FirecrawlAgent",
	"FriendlyCrawler",
	"Gemini-Deep-Research",
	"Google-CloudVertexBot",
	"Google-Firebase",
	"Google-NotebookLM",
	"GoogleAgent-Mariner",
	"GoogleOther",
	"GoogleOther-Image",
	"GoogleOther-Video",
	"iaskspider/2.0",
	"IbouBot",
	"ICC-Crawler",
	"ImagesiftBot",
	"img2dataset",
	"ISSCyberRiskCrawler",
	"Kangaroo Bot",
	"LinerBot",
	"Linguee Bot",
	"Meta-ExternalAgent",
	"meta-externalfetcher",
	"Meta-ExternalFetcher",
	"meta-webindexer",
	"MistralAI-User",
	"MistralAI-User/1.0",
	"MyCentralAIScraperBot",
	"netEstate Imprint Crawler",
	"NovaAct",
	"OAI-SearchBot",
	"omgili",
	"omgilibot",
	"OpenAI",
	"Operator",
	"PanguBot",
	"Panscient",
	"panscient.com",
	"Perplexity-User",
	"PerplexityBot",
	"PetalBot",
	"PhindBot",
	"Poseidon Research Crawler",
	"QualifiedBot",
	"QuillBot",
	"quillbot.com",
	"SBIntuitionsBot",
	"ShapBot",
	"Sidetrade indexer bot",
	"TerraCotta",
	"Thinkbot",
	"TikTokSpider",
	"Timpibot",
	"VelenPublicWebCrawler",
	"WARDBot",
	"Webzio-Extended",
	"wpbot",
	"YaK",
	"YandexAdditional",
	"YandexAdditionalBot",
	"YouBot",
]);

export const generatePolicies = (agents: Set<string>): Policy[] => {
	return [...agents].map((agent) => ({
		disallow: "/",
		userAgent: agent,
	}));
};
