name: Acceptance Tests

on:
    deployment_status:

jobs:
    e2e:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        if: github.event.deployment_status.state == 'success'

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 14
                  cache: yarn

            - name: Install dependencies
              run: yarn --frozen-lockfile --prefer-offline

            - name: Install Playwright
              run: npx playwright install --with-deps

            - name: Run Playwright tests
              run: yarn test:e2e
              env:
                  APP_URL: ${{ github.event.deployment_status.target_url }}
